#! /usr/bin/python3

# STRINGBEAN v 0.01
# copyright 2023, by Dirty Brie
# licensed under:
# GNU GENERAL PUBLIC LICENSE v3.0

import random
import string
import argparse
import os
import getpass
import sys
os.getcwd()
user = getpass.getuser()
path = f"/home/{user}/Documents/stringbean"
chk_path = f"/home/{user}/Documents"

# ASCII TABLE
char = string.ascii_letters
numb = '0123456789'
spec = string.punctuation
# Characters and Numbers
charnumb = char + numb
# Characters and Special Characters
charspec = char + spec
# Numbers and Special Characters
numbspec = numb + spec
# Characters, Numbers and Special Characters.
cns = char + numb + spec

# LIMITS
str_limit = 21
lst_limit = 200001

class banners():
	def __init__(self):
		pass

	def str_machine(self):
		print('''
               n
       	        nm
        	  MM
        	  ### 
        	f#$$#
               __$$$$_  
               | \##
	_______|  |____ 
	|___X     X __| 
	|____xxxxx____| 
	|r E 3 f $ # v| 
	|v_v_v_v_v_v_v| 
	|_____________| 
		''')
	
	def help_sb(self):
		print('''
	STRINGBEAN v0.01
	by Dirty Brie
	****************  
	_________________________________________________
	usage:
	There must be 2 arguments and
	both arguments must be integers
	the First argument is how long the texts will be
	the Second is how many lines the text file will have
	The limit for the length: 20
	the limit for lines: 200,000

	ex:                      output:
	stringbean 8 1000       | (8 letters, 1000 lines)
	stingbean 10 300        | (10 letters, 300 lines)

	see the script for more info :)
	__________________________________________________
		''')

def random_string_generator(str_size, allowed_chars):
    return ''.join(random.choice(allowed_chars) for i in range(str_size))

class checkdir(object):
	def __init__(self):
		pass

	def chkdirs(self, chkpath):
		user = getpass.getuser()
		if not os.path.isdir(chkpath):
			print(f"stringbean needs a Documents directory in /home/{user}")
			sys.exit(1)
		else:
			return

	def mkdir(self, path):
		if not os.path.isdir(path):
			os.mkdir(path)
			print(f"Creating Directory: home/{user}/Documents/stringbean")
		elif os.path.isdir(path):
			return

class strgen(object):
	def __init__(self, strlen=False, lstlen=False):
		self.strlen = strlen
		self.lstlen = lstlen

	def spitrun(self):
		if args.strlen < str_limit and args.lstlen < lst_limit:
			count = 0
			filename = input("Enter the name you want the file to be: ")
			while count != args.lstlen:
				# Here you can swap charnumb with one of variables at the ASCII Table (lines -56)
				stringbean = random_string_generator(args.strlen, charnumb)
				output = stringbean + "\n"
				with open(f"/home/{user}/Documents/stringbean/{filename}.txt", "a+") as text_file:
					text_file.write(output)
				count += 1
			banners.str_machine()
			print(f"Output file: /home/user/stringbean/{filename}.txt with", args.strlen, "text length and", args.lstlen, "lines")
			return
		else:
			print("Invalid Entry... \nQUITING!!!")

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument("strlen", help="String Length", type=int, default=0, nargs="?")
	parser.add_argument("lstlen", help="List Length/Lines", type=int, default=0, nargs="?")
	args = parser.parse_args()
	banners = banners()
	if not (args.strlen and args.lstlen):
		banners.help_sb()
	else:
		checkdir = checkdir()
		checkdir.chkdirs(chk_path)
		checkdir.mkdir(path)
		strgen = strgen(strlen=args.strlen, lstlen=args.lstlen)
		strgen.spitrun()
		
